services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./backend
    ports:
      - "4000:4000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
